pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    options {
        ansicolor ('xterm')
    }
    parameters {
        choice (name:'action', choices:['apply', 'destroy'], description: 'pick something')
    }
    stages {
        stage ('Init') {
            steps {
                sh """
                cd 01-vpc
                terraform init -reconfigure
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                cd 01-vpc
                terraform plan
                """
            }
        }
        stage('Deploy') {
            when {
                expression {
                    params.action == 'apply'
                }
            }

            
            input {
                message "should we continue ?"
                ok "Yes, we should"
            }
            steps {
                sh """
                cd 01-vpc
                terraform apply -auto-approve
                """
            }

        }

        stage('Destroy') {
            when {
                expression {
                    params.action == 'destroy'
                }
            }

            
            input {
                message "should we continue ?"
                ok "Yes, we should"
            }
            steps {
                sh """
                cd 01-vpc
                terraform destroy -auto-approve
                """
            }

        }
    }
    post {
          failure{
               echo "This runs when pipeline is failed."
            }
          
          always {
                echo "This runs always"
          }
          success {
                 echo "This runs if the pipeline is success"
          }
        }
}