pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    stages {
        stage ('Init') {
            steps {
                sh """
                cd 01-vpc
                terraform init-reconfigure
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                cd 01-vpc
                terraform plan
                """
            }
        }
        stage('Deploy') {
            input {
                message "should we continue ?"
                ok "Yes, we should"
            }
            steps {
                sh """
                cd 01-vpc
                terraform apply -auto-approve
                """
            }
        }
    }
    post {
          failure{
               echo "This runs when pipeline is failed."
            }
          
          always {
                echo "This runs always"
          }
          success {
                 echo "This runs if the pipeline is success"
          }
        }
}